### ISSUE TITLE
Implement Form Validation at Backend Register

### ISSUE THREAD

**Issue by hyperloo** [hyperloo/UrlCompressor-Server#2]
**How is the feature you adding to the App is related to the issue? Please describe.**
1. Name Field: Required, No JS
2. Password Field: Minimum Length: 8, Contains at least 1 special char, 1 number, 1 Capital Letter & 1 Small Letter
3. Email Field: Must be an Email
And send the proper response code with the appropriate message.

**Describe the method/ package through which you have implemented the solution.**
Mention the details about the Package or the method you have used to overcome the issue.

**Comment by 2bit-hack** [comment]
Is it okay if I work on this issue for Hacktoberfest 2020?

**Comment by arnxv0** [comment]
I could work on this for the Hacktoberfest 2020 if you'd like :)

**Comment by hyperloo** [comment]
> 
> 
> Is it okay if I work on this issue for Hacktoberfest 2020?

Hey, @2bit-hack,
Thanks for showing interest. If you need any help with the code, you can contact me. I will be happy to help.

**Comment by hyperloo** [comment]
> 
> 
> I could work on this for the Hacktoberfest 2020 if you'd like :)

Hey @arnxv0,
Thanks for showing interest. This issue is assigned to @2bit-hack as he has asked earlier. You can see for any other issue over this App or any of my other Apps. : )

**Comment by arnxv0** [comment]
> > I could work on this for the Hacktoberfest 2020 if you'd like :)
> 
> Hey @arnxv0,
> Thanks for showing interest. This issue is assigned to @2bit-hack as he has asked earlier. You can see for any other issue over this App or any of my other Apps. : )

Okay cool, thanks for responding :)

**Comment by 2bit-hack** [comment]
> If you need any help with the code, you can contact me. I will be happy to help.

Are you on Discord? We could contact there if necessary.

**Comment by hyperloo** [comment]
Yes, I have. Give me your discord user code.

**Comment by 2bit-hack** [comment]
SierraKilo#0536

**Comment by 2bit-hack** [comment]
Regarding special characters, are any characters that are not uppercase, lowercase, digits considered special?
